**Ejercicio 06**

In [2]:

import numpy as np

In [6]:
A = [[255,34,45,16,24,99],[200,50,67,15,56,88],[165,67,34,26,87,70],[120,100,45,45,56,67],[45,225,35,67,50,44],[36,255,24,78,77,23]]
B = [[0,0,0],[0,255,0],[0,0,0]]
print(np.array(A))
print()
print(np.array(B))
print()
print("==>Matriz reemplzando 50 con la matriz B")
print()
for i in range(len(A)):
    for j in range(len(A[i])):
        if A[i][j] == 50:
            # Reemplazar los elementos adyacentes con la matriz B
            for x in range(i-1, i+2):
                for y in range(j-1, j+2):
                    if x >= 0 and x < len(A) and y >= 0 and y < len(A[i]):
                        A[x][y] = B[x-i+1][y-j+1]

print(np.array(A))
print()



[[255  34  45  16  24  99]
 [200  50  67  15  56  88]
 [165  67  34  26  87  70]
 [120 100  45  45  56  67]
 [ 45 225  35  67  50  44]
 [ 36 255  24  78  77  23]]

[[  0   0   0]
 [  0 255   0]
 [  0   0   0]]

==>Matriz reemplzando 50 con la matriz B

[[  0   0   0  16  24  99]
 [  0 255   0  15  56  88]
 [  0   0   0  26  87  70]
 [120 100  45   0   0   0]
 [ 45 225  35   0 255   0]
 [ 36 255  24   0   0   0]]

