<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h1>Ingeniero Renzo Bolivar - Docente DAIE</h1> </center> 

<center> <h1>Curso : Computación 2</h1> </center> 

<h2><center>Grupo: A2</center></h2>
<h2><center>Alumno: Axel Scott Palma layme</center></h2>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****EJERCICIOS****<tfont>

<center> <h2>Ejercicio 05</h2> </center> 

De la siguiente Matriz:

<img src="https://user-images.githubusercontent.com/19308295/115969585-39509780-a503-11eb-92ac-fd88557e6cfc.png"
    style="width:400px"></img>

* Extraer la matrices de cada color

In [194]:
a = np.array([np.arange(1,6), np.arange(6,11), np.arange(11,16),np.arange(16,21),np.arange(21,26), np.arange(26,31)])
print (a, "\n")

x,y = np.indices((6,5))

verde = np.diag(a,1)
print("La matriz de color verde es: \n", verde, "\n")

azul = np.array([[a[2,0],a[2,1]],[a[3,0],a[3,1]]])
print("La matriz de color azul es: \n", azul, "\n")

rojo = np.array ([(a[0,3],a[0,4]),(a[4,3],a[4,4]),(a[5,3],a[5,4])])
print("La matriz de color rojo es: \n", rojo, "\n")
#print(a[5][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

La matriz de color verde es: 
 [ 2  8 14 20] 

La matriz de color azul es: 
 [[11 12]
 [16 17]] 

La matriz de color rojo es: 
 [[ 4  5]
 [24 25]
 [29 30]] 



![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Documentación de NumPy http://docs.scipy.org/doc/numpy

[2] Travis Oliphant, "Guide to NumPy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf

[3] SciPy Lecture Notes http://scipy-lectures.github.io

[4] Nicolas Rougier, "100 NumPy exercises" http://www.loria.fr/~rougier/teaching/numpy.100/index.html

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)