## EJERCICIO 3
Crea una matriz aleatoria 7x7 y halla los valores mínimo y máximo.
Normaliza la matriz anterior entre 0 y 1.


In [5]:
import numpy as np

In [14]:
m = np.random.randint(100,size=(7,7))
print(m)

[[16 15 52 15 13 27 86]
 [ 4 55 30 29 87 15 93]
 [18 77 57 15  2 93 77]
 [22 49 32 72 47  4 40]
 [15  0 83 33 90 61 59]
 [88 59 47 40 20  3  1]
 [90 15 91 83 23  3 16]]


In [15]:
minimo = m.min()
maximo = m.max()

print(minimo,maximo)

0 93


In [16]:
m = (m - minimo)/(maximo - minimo)
print(m)

[[0.17204301 0.16129032 0.55913978 0.16129032 0.13978495 0.29032258
  0.92473118]
 [0.04301075 0.59139785 0.32258065 0.31182796 0.93548387 0.16129032
  1.        ]
 [0.19354839 0.82795699 0.61290323 0.16129032 0.02150538 1.
  0.82795699]
 [0.23655914 0.52688172 0.34408602 0.77419355 0.50537634 0.04301075
  0.43010753]
 [0.16129032 0.         0.89247312 0.35483871 0.96774194 0.65591398
  0.6344086 ]
 [0.94623656 0.6344086  0.50537634 0.43010753 0.21505376 0.03225806
  0.01075269]
 [0.96774194 0.16129032 0.97849462 0.89247312 0.24731183 0.03225806
  0.17204301]]
