# Universidad Nacional de San Agustin

## Escuela Profesional de Ingenieria de Telecomunicaciones

![Insinia ](https://upload.wikimedia.org/wikipedia/commons/f/f9/Escudo_UNSA.png)

#### Ingeniero Renzo Bolivar-Docente DAIE
#### Curso: Computacion 2

### NUMPY



## NUMPY FUNCIONES BASICAS

### Matriz Unidimencional

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


### Matriz bidimensional

In [3]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
array=np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


## Porque usar numpy

### Cantidad de momoria asignada

In [6]:
array=np.array([[1,2,3,4],[5,6,7,8]] )
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
import sys 
s=range(1000)
print(sys.getsizeof(5)*len(s))

28000


In [8]:
d=np.array(1000)
print(d.size*d.itemsize)

8


#### Velocidad

In [9]:
import time

SIZE=1000000
L1=range(SIZE)
L2=range(SIZE)

start=time.time()
result=[(x,y)for x,y in zip(L1,L2)]
print((time.time()=start)*1000)

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (1773075546.py, line 9)

In [10]:
A1=np.arannge(SIZE)
A2=np.arannge(SIZE)
start=time.time()
result=A1+A2
print((time.time()=start)*1000)

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (988883132.py, line 5)

### Matrices Vacias

#### matriz con numeros igual a 1

In [11]:

unos=np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
ceros=np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
aleatorios=np.random.random((2,2))
print(aleatorios)

[[0.70013163 0.9043987 ]
 [0.24428733 0.30570127]]


In [15]:
vacia=np.empty((3,2))
print(vacia)

[[1.4742527e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]


In [16]:
full=np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


In [17]:
espacio1=np.arange(0,35,5)
print(espacio1)

[ 0  5 10 15 20 25 30]


In [18]:
espacio2=np.linspace(0,2,5,)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


In [19]:
identidad1=np.eye(4,4)
print(identidad1)
identidad2=np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Inspeccionar matrices de Numpy

#### dimensiones de una matriz

In [20]:
a=np.array([(1,2,3),(4,5,6)])
print(a.ndim) #dimensiones de la matriz

2


#### tipo de datos de una matriz

In [21]:
print(a.dtype)

int64


#### Tamaño y forma de una matriz

In [22]:
a=np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


#### Cambio de forma de una matriz

In [23]:
a=np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


#### Seleccionar elementos de una matriz

In [24]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [25]:
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a[0:,2])

[3 7]


### Operacione Matematicas entre matrices de Numpy

#### valor minimo, maximo y la suma

In [26]:
a=np.array([(2,45,800)])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


#### Raiz cuadrada y desviacion de una matriz

In [27]:
a=np.array([(1,4,81),(33,44,50)])
print(np.sqrt(a))  #raiz
print(np.std(a))  #division estandar

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


#### Suma, resta, multiplicacion y division de dos matrices

In [28]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 8 10 12]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [16 25 36]]

[[1. 1. 1.]
 [1. 1. 1.]]


### Ejemplo

In [30]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [33]:
z=np.random.random(30)
m=z.mean()
print(m)

0.567128802787508


In [35]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
